### PR TITLE
[pref] 优化代码以减少重复工作

### PR DESCRIPTION
**Pull request by Luna-Grace**
@fjwxzde set
@fjwxzde run test

### CODE REVIEW

**Comment by fjwxzde** [comment]
Logs:
[PR-Test-20240704.log](https://github.com/user-attachments/files/16099246/PR-Test-20240704.log)

**Review by fjwxzde — DISMISSED** [review]

**Comment by DuckDuckStudio** [comment]
@Luna-Grace 
> This pull request is still a work in progress
> Draft pull requests cannot be merged.

**Review by DuckDuckStudio — APPROVED** [review]

**Comment by DuckDuckStudio** [comment]
@Luna-Grace 还有别的修改吗？

**Comment by DuckDuckStudio** [comment]
image

**Comment by DuckDuckStudio** [comment]
@fjwxzde run test

**Comment by fjwxzde** [comment]
分支 pref → 成功
分支 main → 异常退出

**Review by fjwxzde — APPROVED** [review]

**Review by DuckDuckStudio — APPROVED** [review]

**Pull request merged**
